== Imburse Test
These tests demonstrate: -
Generating a Hmac
Generating a Bearer token
------
Get Access Token - /v1/identity/hmac
Create Order - /v1/order-management
Create Instruction - /v1/order-management/{orderRef}/instruction
------

I believe the raw automation framework is in place and you can get the gist of what has been implemented.
The framework also allows for additional endpoints and tests to be added.

The framework uses:
Cucumber (GIVEN WHEN THEN) Gherkin format, Serenity (mainly for reporting) and Java.

== Assumptions
NOTE: I have identified a couple of issues with the supplied information.
The API Url from Imburse differes from the API URL used
The TenantId on the supplied documentation is incorrect

These issues delayed me somewhat as I had to first understand the domain under test, before discovering these issues.


== Setting up your environment

You can clone this project using the following command:

-----
git clone https://github.com/martintraille/imburse.git
-----

== File structure

Feature files are located here:

----
src/test/resources/features
----

Step definitions are located here:

----
src/test/java/imburse/steps
----

== Build/Run the project

This project uses a Maven build. To run the tests use:

----
mvn clean verify
----

== To run the test in different browsers - e.g. Chrome,  you can use the following:

----


== I have also added tags so you can run whatever scenarios you want.
In my example I have a tag called @BUGFOUND - for the failing tests so you can easily run and check them for yourselves.

To execute only those scenarios with a tag use:

----
mvn clean verify -Dtags=@BUGFOUND
----

== Test Reports

HTML Test reports are located here:

----
src/target/site/serenity/index.html
----
